version: "3.9"

services:
  grafico_postgres:
    container_name: grafico_postgres
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Teste123!@#
      - POSTGRES_DB=grafico
    ports:
      - "5432:5432"
    volumes:
      - grafico_postgres:/var/lib/postgresql/data

volumes:
  grafico_postgres:
